### ISSUE TITLE
Crash with KubeJS 6.1 due to breaking changes

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [impleri/player-skills#71]
**Describe the bug**
Player Skills and other it's modules crashes the modpack when using KubeJS 6.1 making modpack not launchable at all. However, when I was working with 6.0 version of KubeJS, it was loading just fine.

The main reason of using 6.1 and not 6.0 that I want to use some new addons such as Custom Machinery, Loquat and etc. with both Player Skills modules to make a modpack, but have no success due to a bunch of missing methods in newer versions as a modpack developer. (Recipes were rewritten to schemas and etc., you can find announcement with changes [here](https://wiki.latvian.dev/books/kubejs/page/kubejs-61-update))

**To Reproduce**
1. Get an Fabric API or Forge.
2. Install Architectury API, Rhino, KubeJS 6.1 (not 6.0 one)
3. Get Minecraft crashed without any other mods installed with this error:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'kubejs'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/RegistryObjectBuilderTypes
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:25)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/RegistryObjectBuilderTypes
	at net.impleri.playerskills.integration.kubejs.Registries.<clinit>(Registries.java:12)
	at net.impleri.playerskills.integration.kubejs.PlayerSkillsPlugin.init(PlayerSkillsPlugin.java:30)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:106)
	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:132)
	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:22)
	... 12 more
Caused by: java.lang.ClassNotFoundException: dev.latvian.mods.kubejs.RegistryObjectBuilderTypes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```
(this is example for the Fabric ecosystem, the same happens with Forge, let me know if you need logs for both instances, but they're easily can be reproduced)

**Context**
Minecraft version: 1.19.2 (1.18.2 should be fine)
Player Skills version: 1.12.0
KubeJS version: 1902.6.1-build.311
Rhino version: 1902.2.2-build.268
Architectury API version: 6.5.85
Fabric API version: 0.76.0+1.19.2
Forge version: 43.2.21
Forge or Fabric version: Fabric (and Forge affected too)
Server/Client or Solo? Both client and server affected.
Log file: See below for the error. If you need logs, let me know!

Originally it was an instance with 220+ mods installed (435 mods with libs and etc.), so I moved the mod to clean instance with only specified mods here to make sure it is not another mod crashing the whole modpack at start.
Thanks for your work, really useful mod!

**Comment by turnerlewis** [comment]
I also have this very same bug.
