### ISSUE TITLE
Crash on Minecraft 1.19.2 with Player Skills 1.12.0

### ISSUE THREAD

**Issue by AleDev2105** [impleri/player-skills#72]
**Describe the bug**
When I click to start the game the launcher crash. This is latest.log and crash report.

Latest.log below.
And this is the crash report:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-08-03 16:59:50
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:aluminum_block
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.21-universal.jar%23259!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.LangGen.addTranslations(LangGen.java:60) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EELangProvider.m_213708_(EELangProvider.java:65) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.data.DataGenerator.m_123917_(DataGenerator.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.EmendatusEnigmatica.generate(EmendatusEnigmatica.java:121) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.GeneratedPack.<init>(GeneratedPack.java:50) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.lambda$loadPacks$0(EEPackFinder.java:48) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.Pack.m_10430_(Pack.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.m_7686_(EEPackFinder.java:47) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.21-universal.jar%23259!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.LangGen.addTranslations(LangGen.java:60) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EELangProvider.m_213708_(EELangProvider.java:65) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.data.DataGenerator.m_123917_(DataGenerator.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.EmendatusEnigmatica.generate(EmendatusEnigmatica.java:121) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.GeneratedPack.<init>(GeneratedPack.java:50) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.lambda$loadPacks$0(EEPackFinder.java:48) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.Pack.m_10430_(Pack.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.ridanisaurus.emendatusenigmatica.datagen.base.EEPackFinder.m_7686_(EEPackFinder.java:47) ~[EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar%23213!/:2.1.5-build.61+mc1.19.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23254!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 13.5
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 269876488 bytes (257 MiB) / 872415232 bytes (832 MiB) up to 6308233216 bytes (6016 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0x573b5eec Model 0 Stepping 0
	Microarchitecture: x86_64 Rosetta 2 (Virtual Westmere)
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6840.22
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 160.19
	JVM Flags: 8 total; -Xss1M -Xmx6000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: modpack
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Apple M2 GL version 4.1 Metal - 83.1, Apple
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Apple M2
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.21.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.21.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.21.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.21.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.21.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
	Mod List: 
		rhino-forge-1902.2.2-build.268.jar                |Rhino                         |rhino                         |1902.2.2-build.268  |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-MoreSolarPanels-1.19.2-1.5.2.jar         |More Solar Panels             |solarpanels                   |1.19.2-1.5.2        |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.7.jar                         |Cucumber Library              |cucumber                      |6.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.19.2-1.8.2.jar                   |Botarium                      |botarium                      |1.8.2               |COMMON_SET|Manifest: NOSIGNATURE
		ExtendedCrafting-1.19.2-5.1.7.jar                 |Extended Crafting             |extendedcrafting              |5.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-Evolution-1.19.2-1.3.4.jar               |Mekanism: Evolution           |mekaevolution                 |1.19.2-1.3.4        |COMMON_SET|Manifest: NOSIGNATURE
		Easy Mob HealthBar Mod-0.0.1 1.19.2.jar           |Health Bar Mod                |healthbarmod                  |0.0.1-1.19          |COMMON_SET|Manifest: NOSIGNATURE
		KubeJSREIRuntime-1.0.jar                          |KubeJSREIRuntime              |kubejsreiruntime              |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.63.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.63              |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.3.103-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.103             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.21-universal.jar                |Forge                         |forge                         |43.2.21             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		adtetra-1.0.1.jar                                 |Ad Tetra                      |adtetra                       |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EE_Thermal_Addon-1.0.0-build.7+mc1.19.2.jar       |EE:Thermal                    |ee_thermal_addon              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		cofh_core-1.19.2-10.2.1.40.jar                    |CoFH Core                     |cofh_core                     |10.2.1              |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_core-1.19.2-10.2.0.5.jar                  |Thermal Series                |thermal                       |10.2.0.5            |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		EE_Mekanism_Addon-1.0.1-build.11+mc1.19.2.jar     |EE:Mekanism                   |ee_mekanism_addon             |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		systeams-1.19.2-1.4.1.jar                         |Thermal Systeams              |systeams                      |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		Capsule-1.19.2-7.0.98.jar                         |Capsule                       |capsule                       |1.19.2-7.0.98       |COMMON_SET|Manifest: NOSIGNATURE
		thermal_innovation-1.19.2-10.2.0.18.jar           |Thermal Innovation            |thermal_innovation            |10.2.0.18           |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		titanium-1.19.2-3.7.3-27.jar                      |Titanium                      |titanium                      |3.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.8.1.jar                       |Jade                          |jade                          |8.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		EmendatusEnigmatica-2.1.5-build.61+mc1.19.2.jar   |Emendatus Enigmatica          |emendatusenigmatica           |1.19.2-2.1.5        |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.2-1.0.20.jar         |Resourcefulconfig             |resourcefulconfig             |1.0.20              |COMMON_SET|Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.632.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.632             |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		tetra-1.19.2-5.4.0.jar                            |Tetra                         |tetra                         |5.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.9.13.jar                     |Mekanism                      |mekanism                      |10.3.9              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.9.13.jar           |Mekanism: Generators          |mekanismgenerators            |10.3.9              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismAdditions-1.19.2-10.3.9.13.jar            |Mekanism: Additions           |mekanismadditions             |10.3.9              |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		Thermal And Space 1.19.2-3.0.3.jar                |Thermal And Space             |thermal_and_space             |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		thermal_foundation-1.19.2-10.2.0.47.jar           |Thermal Foundation            |thermal_foundation            |10.2.0.47           |COMMON_SET|Manifest: NOSIGNATURE
		thermal_expansion-1.19.2-10.2.0.21.jar            |Thermal Expansion             |thermal_expansion             |10.2.0.21           |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.9.13.jar                |Mekanism: Tools               |mekanismtools                 |10.3.9              |COMMON_SET|Manifest: NOSIGNATURE
		lootjs-forge-1.19.2-2.9.0.jar                     |LootJS                        |lootjs                        |2.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-forge-1902.6.1-build.348.jar               |KubeJS                        |kubejs                        |1902.6.1-build.348  |ERROR     |Manifest: NOSIGNATURE
		ftb-library-forge-1902.4.1-build.236.jar          |FTB Library                   |ftblibrary                    |1902.4.1-build.236  |COMMON_SET|Manifest: NOSIGNATURE
		item-filters-forge-1902.2.9-build.51.jar          |Item Filters                  |itemfilters                   |1902.2.9-build.51   |COMMON_SET|Manifest: NOSIGNATURE
		kubejs-mekanism-1902.1.5-build.15.jar             |KubeJS Mekanism               |kubejs_mekanism               |1902.1.5-build.15   |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1902.2.14-build.123.jar           |FTB Teams                     |ftbteams                      |1902.2.14-build.123 |COMMON_SET|Manifest: NOSIGNATURE
		ftb-chunks-forge-1902.4.1-build.290.jar           |FTB Chunks                    |ftbchunks                     |1902.4.1-build.290  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-industrial-contraptions-1900.1.7-build.221.jar|FTB Industrial Contraptions   |ftbic                         |1900.1.7-build.221  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-quests-forge-1902.5.3-build.258.jar           |FTB Quests                    |ftbquests                     |1902.5.3-build.258  |COMMON_SET|Manifest: NOSIGNATURE
		myrtrees-forge-1.2.0-build.32.jar                 |Myrtrees                      |myrtrees                      |1.2.0-build.32      |COMMON_SET|Manifest: NOSIGNATURE
		player-skills-1.19.2-1.12.0.jar                   |Player Skills                 |playerskills                  |1.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		probejs-5.3.0-forge-hotfix.jar                    |ProbeJS                       |probejs                       |5.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		polylib-forge-1900.0.2-build.73.jar               |PolyLib                       |polylib                       |1900.0.2-build.73   |COMMON_SET|Manifest: NOSIGNATURE
		ftbbackups2-forge-1.19.2-1.0.19.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.19              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_dynamics-1.19.2-10.2.1b.14.jar            |Thermal Dynamics              |thermal_dynamics              |10.2.1b             |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		ad_astra-forge-1.19.2-1.12.7.jar                  |Ad Astra                      |ad_astra                      |1.12.7              |COMMON_SET|Manifest: NOSIGNATURE
		Ad-Astra-Giselle-Addon-forge-1.19.2-1.16.jar      |Ad Astra!: Giselle Addon      |ad_astra_giselle_addon        |1.16                |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 769970c3-2e2b-4654-9778-8e1e1d93f114
	FML: 43.2
	Forge: net.minecraftforge:43.2.21

**To Reproduce**
Simply start the game.

**Context**
Minecraft version: 1.19.2
Forge or Fabric version: Forge
Server/Client or Solo?
Player Skills version: 1.12.0
Log file:[ Try using [mclogs](https://mclo.gs/) instead of attaching directly to this.](https://api.mclo.gs/1/raw/RfwxOHG)

**Comment by impleri** [comment]
I suspect this is a dupe of #71
